# Generated by Django 5.0.4 on 2024-05-08 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alias', models.CharField(max_length=100)),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Coordinates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=100)),
                ('address3', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('zip_code', models.CharField(max_length=10)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('display_address', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('alias', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('image_url', models.CharField(max_length=250)),
                ('is_closed', models.BooleanField()),
                ('url', models.CharField(max_length=250)),
                ('review_count', models.IntegerField()),
                ('rating', models.DecimalField(decimal_places=1, max_digits=2)),
                ('price', models.CharField(max_length=10)),
                ('phone', models.CharField(max_length=20)),
                ('display_phone', models.CharField(max_length=20)),
                ('distance', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categories', models.ManyToManyField(to='home.category')),
                ('coordinates', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.coordinates')),
                ('location', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='home.location')),
            ],
        ),
    ]
