# Generated by Django 5.0.4 on 2024-05-08 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='price',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='address3',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
