# Generated by Django 5.0.4 on 2024-05-08 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_alter_business_price_alter_location_address3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='categories',
            field=models.ManyToManyField(null=True, to='home.category'),
        ),
        migrations.AlterField(
            model_name='business',
            name='coordinates',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.coordinates'),
        ),
        migrations.AlterField(
            model_name='business',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='address2',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
