# Generated by Django 5.0.4 on 2024-05-08 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_alter_location_address1_alter_location_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='rating_img_url',
            field=models.CharField(default='Review_Ribbon_small_16_0.0@2x.png', max_length=250),
        ),
        migrations.AlterField(
            model_name='business',
            name='categories',
            field=models.ManyToManyField(to='home.category'),
        ),
    ]
