# Generated by Django 5.0.4 on 2024-05-08 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_business_rating_img_url_alter_business_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='coordinates',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.coordinates'),
        ),
        migrations.AlterField(
            model_name='business',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='home.location'),
        ),
    ]
